### ISSUE TITLE
Can't build project when source generator is referenced on MacOS

### ISSUE THREAD

**Issue by davidwengier** [wieslawsoltes/SourceGenerators#3]
I'm trying to use the source generators in my project, and referencing from nuget is working on Windows, but on MacOS the build fails due to a missing native library reference.

Build log: https://github.com/davidwengier/Trains.NET/pull/158/checks?check_run_id=1304612100#step:4:814
Error:
>  CSC : error SI0000: Error in the SvgSourceGenerator generator: 'System.TypeInitializationException: The type initializer for 'Svg.Skia.SKSvgSettings' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: libSkiaSharp assembly:<unknown assembly> type:<unknown type> member:(null) [/Users/runner/work/Trains.NET/Trains.NET/src/Trains.NET.Rendering.Skia/Trains.NET.Rendering.Skia.csproj]

This also fails on my MacBook Pro, so it's not just GitHub Actions. I'm guessing there is some way to specify in the nuget package to copy the native dependencies into the source generator package, but I don't know what it is :)

**Comment by wieslawsoltes** [comment]
Does this compile https://github.com/wieslawsoltes/SourceGenerators/tree/master/samples/Svg.Skia.SourceGenerator.NuGet

**Comment by davidwengier** [comment]
No, I get the same error compiling that project locally. I've attached a binlog in case it helps:

[msbuild.binlog.zip](https://github.com/wieslawsoltes/SourceGenerators/files/5435900/msbuild.binlog.zip)

**Comment by wieslawsoltes** [comment]
I am integrating this repo into https://github.com/wieslawsoltes/Svg.Skia and moving to `net5.0` target.
